license="MIT"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Groupix05/DynamicTrees-Generator/issues"

[[mods]]
modId="dtfish_of_thieves"
version="${file.jarVersion}"
displayName="Dynamic Trees for Fish of Thieves"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamictrees"
logoFile="logo.png"
credits=""
authors="Groupix05"
description='''
Adds Dynamic Trees compatibility for Fish of Thieves.
'''

[[dependencies.dtfish_of_thieves]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtfish_of_thieves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtfish_of_thieves]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtfish_of_thieves]]
    modId="fishofthieves"
    mandatory=true
    versionRange="[3.1.1,)"
    ordering="AFTER"
    side="BOTH"
